export const referralRegistryAbi = [
  {
    type: "function",
    name: "registerCode",
    inputs: [{ name: "code", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setReferrer",
    inputs: [{ name: "referrer", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "recordReferral",
    inputs: [
      { name: "trader", type: "address" },
      { name: "referrer", type: "address" },
      { name: "token", type: "address" },
      { name: "tradeVolume", type: "uint256" },
      { name: "rewardAmount", type: "uint256" },
      { name: "quoteAsset", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimRewards",
    inputs: [{ name: "quoteAsset", type: "address" }],
    outputs: [{ name: "amount", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "referrerOf",
    inputs: [{ name: "trader", type: "address" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "codeOwner",
    inputs: [{ name: "code", type: "bytes32" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimableRewards",
    inputs: [
      { name: "referrer", type: "address" },
      { name: "quoteAsset", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalReferralVolume",
    inputs: [{ name: "referrer", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "referralCount",
    inputs: [{ name: "referrer", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
] as const;
